### ISSUE TITLE
SysUtils.Now looks overencumbered

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#125]
Try to implement a simpler (faster) version of SysUtils.Now, as it looks like native Now makes enormous amount of unneeded conversions. Or maybe these conversions are different for different platforms?
Anyway this procedure is called in time-critical sections of the code, so replacing it by something faster in World.Manage would be much encouraged.
Maybe, use GetTickCount? And fix FPS according to this value.
GetTickCount discretnes is ~15-17ms, 30 FPS is 33 ms, 60 FPS is 17 ms. Therefore this is a bad idea, as it's accuracy is not good enough.
Moreover, "Now" is updated synchronously with GetTickCount, so it's really a bad idea to optimize FPS this way :)

Let's imagine a situation, when the game has 1 tick of MainThread per frame to do World.Manage. Such management will consume 0.5 seconds for 30 FPS.
Due to the tick may be incomplete at World.Manage start:
0.25 seconds average at 30 FPS if "the next" tick is being caught
0.75 seconds average at 30 FPS if "the one after next" tick is being caught.

**Comment by eugeneloza** [comment]
Actually its most demanded in the Overworld, so 2 (1.5) ticks per frame is rather enough for the goal as 30-40FPS will be the goal FPS for this case. So, maybe, yes, there should be 1 full tick + some remnant of the last frame for managing procedure.

**Comment by eugeneloza** [comment]
This looks plausible:
```
T := GetTickCount;
doRender;
repeat
  doManage;
until T+2<GetTickCount;
```

**Comment by michaliskambi** [comment]
CastleTimeUtils has:
- Timer and TimerSeconds to measure time passed.
- ProcessTimer and ProcessTimerSeconds to measure time passed only in your process (on Unix it's possible to measure only the time spend within your own process, which is useful to measure the speed of your own routines, and be at least partially independent from other applications slowing down your system at the same time).

Use like this:

```
var
  TimeStart: TTimerResult;
  Seconds: TFloatTime;
begin
  TimeStart := Timer;
  ...  do something ...
  Seconds := TimerSeconds(Timer, TimeStart);
  Writeln('Seconds passed: ', Seconds:1:2);
end;
```

Just posting, in case it's useful to you here :)

**Comment by eugeneloza** [comment]
Thanks a lot, Michalis!
I've been planning to investigate CastleTimeUtils soon :) But as far as I remember Timer has the same discreteness (~60FPS) as Now, right?
Anyway, I'll study this issue, I've almost got rid of direct access to SysUtils.Now, so it won't be hard to switch to CastleTimeUtils.Timer.

**Comment by michaliskambi** [comment]
CastleTimeUtils routines mostly call OS-specific functions directly, so they have as much precision as possible while being fast.

- On Windows, it depends on QueryPerformanceFrequency . I expect it's at least 1000 units per second, as QueryPerformanceXxx family is advertised as better than GetTickCountXxx family.
- On Unix, it uses gettimeofday, which has 1000 * 1000 units per second.

Note that you cannot trust the precision declared this way, it's only a theoretical precision. E.g. on Unix gettimeofday may actually only report times equal to N * 1000, and in practice have only 1000 *different* units per second. (No, I did not observe it, I'm just warning not to trust my theoretical values above :) )

In any case, these call the most precise time-measuring routines I could find back in the days :) They are used to measure FPS, so they really need to be much more precise than 60 units per second.

BTW, are you sure SysUtils.Now has only 60 changes per second? That would be surprising. Looking in FPC code,
- On Unix, SysUtils.Now just calls gettimeofday, so it should have 1000 * 1000 precision, if the OS can give it. 
- On Windows, SysUtils.Now just calls Windows.GetLocalTime which returns _SYSTEMTIME which should have 1000 precision.

**Comment by michaliskambi** [comment]
BTW (and this is a little subjective judgement from my side), but looking at SysUtils.Now, it doesn't really make an "enormous unneeded convertions" :) It's mostly a call to OS followed by a call to ComposeDateTime , which adds simple float addition + trunc + frac. The overhead should be really small.

If the time spend doing SysUtils.Now is noticeable in your usecase, then you may as well be noticing the time needed for the OS call (like gettimeofday) to read the clock. And this is unavoidable. The solution may be to just check the time less often, make e.g. 10 calculations within a loop before checking the clock.

**Comment by eugeneloza** [comment]
Yep, you're right!
Tested at DebianLinux:
```
SysUtils: 3653 times 2737 mks (i.e. 365 FPS)
CastleTime: 316917 times 32 mks (i.e. 31250 FPS, however it might be higher due to output lags)
CPUTicks: 3652 times 2738 mks (i.e. 365 FPS)
reference: 36 ms (just asignment of a variable)
SysUtils: 10035 ms (reading Now)
CastleTime: 8190 ms (reading Timer and preforming TimerSeconds)
CPUTicks: 8039 ms (reading GetTickCount64)
```
[TimerTest.tar.gz](https://github.com/eugeneloza/decoherence/files/1219729/TimerTest.tar.gz)

That makes CastleTimeUtils 100 times more accurate and 20% faster than SysUtils.Now. Looks great :) Thanks a lot!

**Comment by eugeneloza** [comment]
> The solution may be to just check the time less often

Yes, I already have this one for Actors. However, for World.Manage i still require more fine-tuning of the FPS. Looks like Timer exactly suits my needs :)

**Comment by eugeneloza** [comment]
Possible optimizations test:
```
CastleTime: 8183 ms
CastleTimeInt: 8155 ms (+0.3% speed) no conversion to TFloatTime + inline
LinuxTimer: 8028 ms (+1.9% speed) pure FpGettimeofday usec access + inline
```
So, basically it's hardly worth any further attention. CastleTimeUtils solves my issue perfectly.

**Comment by michaliskambi** [comment]
> That makes CastleTimeUtils 100 times more accurate and 20% faster than SysUtils.Now. Looks great :) Thanks a lot!

Cool, I think I never measured these gains precisely. I see that you measure the accuracy by looking how many times they increase within a fixed time slice, very nice! :)

Note that both `CastleTimeUtils.Timer` and `SysUtils.Now` call `gettimeofday` under the hood on Unix, if I analyzed the FPC code correctly. This, together with your measurements, implies that:

- The accuracy difference must come from the fact that SysUtils.Now squeezes the current time into TDateTime value. TDateTime is internally a Double ( https://www.freepascal.org/docs-html/rtl/system/tdatetime.html , http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/System_TDateTime.html ), with the fraction part describing part of the day (24h, so 24 * 60 * 60 seconds). In contrast, our Timer puts the value into TFloatTime, which is also Doube, but the fraction is just "a fraction of the second". Looks like this approach gives us good gains.

- The speed difference probably comes from the fact that we avoid ComposeDateTime each time.

Thanks for the detailed testing!

**Comment by eugeneloza** [comment]
> the fact that we avoid ComposeDateTime each time

Yes, exactly what I've meant by "overencumbered" :D

But I've made another test with... well... interesting results:

CastleTime: 309253 times 32 mks
Thread: 309253 times 32 mks
...
reference: 37 ms
**ThreadedTimer: 64 ms**

This is a very "strange" but efficient way to get a timer. It just calls FpGettimeofday (better CastleTimeUtils.Timer) in a thread and returns last known value if the thread is not finished. The problem is that whatever the "last" inteval was, it will return previous known value. So it's suitable only for managing extremely frequent time access, i.e. like in World.Manage. However, it works almost as fast as "reference" (which is just assigning a variable). What do you think about such approach?
[TimerTestThreaded.tar.gz](https://github.com/eugeneloza/decoherence/files/1219767/TimerTestThreaded.tar.gz)

**Comment by eugeneloza** [comment]
The fact is that I'll have a lot of management in Overworld. Tasks are sorted by priority, so that:
```
repeat
  preform_the_next_management_task;
until Timer-T0>1/Goal_FPS;
```
so "Timer" will be executed several dozens, or, maybe hundred times per frame. Each call takes approx. 1 microsecond. I.e. 100 management operations will "waste" 0.1 milisecond of precious Main Thread time :) By threads it can be lowered down to negligible 0.005 ms without any significant drawbacks.

**Comment by eugeneloza** [comment]
> The accuracy difference must come from the fact that SysUtils.Now squeezes the current time into TDateTime value.

Not exactly sure about this statement, because SysUtils.Now is absolutely synchronous with GetTickCount64 (which obviously isn't squeezed into anything).

**Comment by michaliskambi** [comment]
> The problem is that whatever the "last" inteval was, it will return previous known value

Beware that setting 64-bit values may not be atomic. I suppose it is not guaranteed to be atomic (especially on 32-bit systems), this requires googling / asking on FPC list. In Java, it's not atomic. In this case, when one thread does "X := something" and X is `Int64` or `QWord`, then another thread may see X in "half-updated" state (32-bits updated, the other 32-bits not yet; which ones are updated first?, this may depend on CPU endianess).

Yes, in case of time, usually only the least-meaningful bits change... but once upon a time, the more-meaningful half also changes.

So you would need to secure access to X with a critical section or something similar, which probably makes the access (from both threads) much slower.

So, I would discourage it, using threads is opening a can of problems here. 

In general, I see that I'm much, much, much, much... more careful when it comes to threads than you :) Synchronizing common knowledge between threads is hard. And errors, as you can see in above example, can be 1. CPU-specific, 2. occur only from time to time. There's nothing worse to debug than an application that crashes randomly only once per week.

- As for your later note, I understand that the solution without thread is actually cool and fast enough for the current use, and the thread was just an experiment? :) In general, my intuition would tell me that this should be doable without threading, and "if asking for Timer takes too much time, than you're asking for Timer too often".

- If you would be very, very persistent and really wanted to use a thread solution, I would probably advice to just use 32-bit GetTickCount, since setting 32-bit values is most probably atomic on all modern platforms (but don't take my word on this, this should be documented somewhere in FPC docs). You can use deprecated  32-bit GetTickCount, or use GetTickCount64 trimmed to the least-significant 32-bits. Make sure that is starts from 0 when your game starts (It's probably not guaranteed by FPC on Unix, but you can do it yourself by always subtracting the initial GetTickCount64 measurement from all further measurements). And communicate with other thread only using this 32-bit milisecond value.

  This gives you a stable solution for 49 days, when the 32-bit GetTickCount will wrap :)

> Not exactly sure about this statement, because SysUtils.Now is absolutely synchronous with GetTickCount64 (which obviously isn't squeezed into anything).

You're right. I must have understood the FPC code incorrectly then, but I cannot catch my error now...

- rtl/unix/sysutils.pp implements DoGetLocalDateTime that extracts full accuracy from fpgettimeofday
- it called by GetLocalTime in the same file
- GetLocalTime is called by `Now` in rtl/objpas/sysutils/dati.inc .

Well, it's entirely possible that I don't see something that complicates this scenario. One would need to place test Writelns in RTL code, and recompile RTL, to check, for now I'll leave it :)

**Comment by eugeneloza** [comment]
> thread was just an experiment

Yes, that was an experiment :) Thou tempting, I too understand it may be a fail-unsafe solution :)

> So you would need to secure access to X with a critical section or something similar, which probably makes the access (from both threads) much slower.

Wrapped access to FpGettimeofday in a critical session, there was no (visible) slow-down. But yes, I'll have to be very careful with that :) I'll make some implementation of in-game Timer based on calling  CastleTimeUtils function and by thread, so it'll be easy to switch back/forward at any second.

Globally, I'm thinking of making an in-game option (or even pair of executables, like by compiler configuration) for "speed" (which will try to unload all the stuff into a thread, giving the user clear understanding that it might fail badly :)) or "reliability" (which will use only the main thread, unless thread-safety is obvious, thou it'll work up to 2 times slower).

**Comment by eugeneloza** [comment]
> There's nothing worse to debug than an application that crashes randomly only once per week.

Yes, that hurts, I know :) I'm still hunting for a memory leak #12 which appears once in a while and actually there is absolutely no hint on why it happens, the heaptrc points to a clean line of code...

**Comment by michaliskambi** [comment]
> Globally, I'm thinking of making an in-game option (or even pair of executables, like by compiler configuration) for "speed" (which will try to unload all the stuff into a thread, giving the user clear understanding that it might fail badly :)) or "reliability" (which will use only the main thread, unless thread-safety is obvious, thou it'll work up to 2 times slower).

You'll have a difficult decision then choosing which one should be the "default" :) I vote for the "reliable" one!

**Comment by eugeneloza** [comment]
Yes, but this way I may leave the decision for some day "later" :)

**Comment by eugeneloza** [comment]
Good news, "Now" function is thread-safe in Windows: https://social.msdn.microsoft.com/Forums/vstudio/en-US/9aa49cdf-54b9-4ca5-a32a-ed5bae9088ab/are-getlocaltime-getsystemtime-threadsafe-?forum=vcgeneral and in Linux http://developerweb.net/viewtopic.php?id=5360

**Comment by eugeneloza** [comment]
And LastTimer: TTimerResult; in CastleTimeUtils - isn't :)

**Comment by michaliskambi** [comment]
> And LastTimer: TTimerResult; in CastleTimeUtils - isn't :)

Indeed.

This is a workaround for a problem on an obscure Android device --- the `LastTimer` check can be just put under `$ifdef ANDROID`. I left this check everywhere, to see whether the same problem will be detected on some non-Android platform, but it never was. I placed it under `$ifdef ANDROID` now, committed to CGE. So Timer is thread-safe now on non-Android.

But in general we cannot guarantee that Timer is thread-safe on all platforms, so you should not depend on it being thread-safe anyway... This is a problem with trying to use threads, things are just not easy :) 

- We cannot just remove the `LastTimer` mechanism or we break games behavior on that nasty Android phone. (Things can behave weirdly if your time increases by a negative value once in a while...)
- And introducing synchronization (like critical sections) around `LastTimer` access will make this code slower, even for single-threaded applications. 
- Some compromise (that keeps single-threaded apps on that nasty Android device correct, and makes all single- and mult-threaded apps on all other devices correct) would be to make `LastTimer` a `threadvar`. But this is also not possible, as not everyone has `uses cthreads` in their uses clause, and we should not require it now without a good reason.

If you want to use a separate thread to query the time (remember that I discourage it in every comment), you're probably safer using a non-CGE function for that. This will be guaranteed to stay thread-safe.

**Comment by eugeneloza** [comment]
Yes, thanks a lot! I've been thinking either of making a "stripped copy" of CastleTimeUtils for this reason. In Management there is no problem if time accidentally "goes back" it'll just make the frame a bit longer. And of course, threaded timer will be optional. I'm thinking of a compiler directive to cover that...

**Comment by eugeneloza** [comment]
Looks like Linux version and base implementation is finished... I will need to fix Windows version thou.
