### ISSUE TITLE
Debug unit

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#244]
Debug levels and initialization
-1: all debug off
0: - base level
1: important
10: not very important
20: unimportant
100+: verbose

**Comment by michaliskambi** [comment]
P.S. If you need a boolean variable to make the internal operations of Castle Game Engine to be less talkative in the logs, let me know :) Currently, _some_ logs are printed to the log always, unconditionally (e.g. OpenGL info when the window opens), I have a TODO to eventually add a boolean flag to turn them off, to have a 100% clean log output (controlled only by you) if needed

**Comment by eugeneloza** [comment]
No-no :). I need a "wrapper" for `CastleLog` (almost finished) that would filter out some errors/information reports. E.g. I often get lost in "error" reports which will be addressed later, and it's difficult to track the important messages relative to issues I'm currently working at in a thousand of "load success" reports.
I've also added a "report" on class that has sent the log, e.g. by `dLog(Self,message)`. I'll upload the commit in the evening.

**Comment by eugeneloza** [comment]
The "heart" of the approach looks like:
```
procedure dLog(const LogLevel: integer; const aObj: TObject; const aPrefix, aMessage: string);
var objName: string;
begin
  if Verbosity <= 0 then Exit;
  if Verbosity >= LogLevel then begin
    if aObj<>nil then objName := ' in '+aObj.ClassName else objName := '';
    WriteLnLog(aPrefix+objName,aMessage)
  end;  
end;
```

**Comment by eugeneloza** [comment]
Done.
Here's the file: https://github.com/eugeneloza/decoherence/blob/master/src/decolog.pas
