### ISSUE TITLE
Move all autogenerated files to subfolder

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#263]
Namely move
https://github.com/eugeneloza/decoherence/blob/master/src/castletexturefont_linbiolinumrg_16.pas (see also #227)
https://github.com/eugeneloza/decoherence/blob/master/src/decoloadembedded.image_data
and
https://github.com/eugeneloza/decoherence/blob/master/src/decoloadembedded.pas
to `/src/generated/` subfolder

LPI file should be correspondingly updated.

**Comment by gfranco93** [comment]
I would like to help with this

**Comment by eugeneloza** [comment]
@gfranco93 , you're welcome! Just make a fork, create a subfolder and move the files there.

It's also would be nice if you could run Lazarus and update the project files accordingly: use Project>Project Inspector menu it'll show that these files went missing after you moved them. However it might argue that you don't have Castle Game Engine installed. But it shouldn't be a problem, just readd the moved files again (they'll be crossed out) and add the directory (you'll be prompted to) to all compile modes (Debug/Release/Normal).
