### ISSUE TITLE
Make generated pas-fonts consume less memory

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#265]
Check https://github.com/castle-engine/castle-engine/tree/master/tools/texture-font-to-pascal documentation on how to limit character set of the generated files, e.g. I need only numbers 0..9 and a dot symobl for 100-sized font.
Like it's done in https://github.com/eugeneloza/decoherence/blob/master/src/decofont.pas#L113
crossref #227

**Comment by michaliskambi** [comment]
Castle Game Engine manual about this: https://castle-engine.sourceforge.io/manual_text.php :)

**Comment by eugeneloza** [comment]
Thanks a lot @michaliskambi I was absolutely sure I've read that somewhere, but forgotten where :) Hey, I can easily implement that one in `Constructor`. Seems easy enough to keep fonts issue more dynamic (no need to reboot to Win).
