### ISSUE TITLE
Switch to GenericCollection

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#268]
To solve https://github.com/eugeneloza/decoherence/issues/96 once and for all :)
Check examples https://github.com/dathox/generics.collections/tree/master/examples
This should replace all generic lists based on deprecated `FGL`/`CastleGenericLists` units. It's not much work (unless the approach is very different, which shouldn't be) but being very careful is required because a lot of different types of lists are used in the game.

**Comment by eugeneloza** [comment]
Not as easy as I'd expect it :) Absolutely no documentation and very blurry examples. Should it be similar to Delphi's Generic.Collection?

**Comment by michaliskambi** [comment]
Yes, Delphi and FPC have compatible Generics.Collections units. So most of the documentation on http://docwiki.embarcadero.com/Libraries/Tokyo/en/System.Generics.Collections should apply also to FPC Generics.Collections. See also my guide on http://castle-engine.io/modern_pascal_introduction.html#generic-containers-section , it shows the most important things (adding, sorting, using the dictionary etc.)

**Comment by eugeneloza** [comment]
Yes, thanks a lot!

**Comment by eugeneloza** [comment]
> /modern_pascal_introduction.html
Aw... I totally missed this new part (put it into a to-do list and successfully forgot to do). It's untranslated too... I should fix this :)

**Comment by eugeneloza** [comment]
Almost done.
