### ISSUE TITLE
GetFolderContent(URL, pattern):TStringList;

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#281]
A function to Get contents of a folder and return a list of URL to the files of specified type. Important for Constructor automation (e.g. get list of tiles, placeholders, fonts, images, etc.)

**Comment by michaliskambi** [comment]
You can use CastleFindFiles to construct this :)

**Comment by eugeneloza** [comment]
Cool, thanks! I'll check it out.
