### ISSUE TITLE
Make a version.bat script

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#284]
Make a windows equivalent of https://github.com/eugeneloza/decoherence/blob/c14962ba522634e2a7b74e0ea7e41e6eb2350951/version.sh
Practically it just extracts "current folder name" and writes it to `src/version.inc` enclosed in apostrophes.
That's how the result looks like: https://github.com/eugeneloza/decoherence/blob/c14962ba522634e2a7b74e0ea7e41e6eb2350951/src/version.inc

**Comment by DeeJay-NuKe** [comment]
I'll do it

**Comment by eugeneloza** [comment]
Thanks a lot! It's working perfectly!

**Comment by DeeJay-NuKe** [comment]
Cheers :)
