### ISSUE TITLE
Argument cannot be assigned to (Generics.Collections)

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#291]
While Generics.Collections work flawlessly in all cases, they don't work for `NAV` with "_Argument cannot be assigned to_" error. Hmm... why? `TList` works perfectly elsewhere... But for this specific list `TList.Items` is read-only (actually I can easily write `TList.Items[i].SomeField` in other situations, but not `Nav.Items[i].Blocked: boolean`). Still had to leave `CastleGenericLists` use here:
https://github.com/eugeneloza/decoherence/blob/master/src/deconavigationnetwork.pas#L60

**Comment by eugeneloza** [comment]
Yes, this is a heavy bug (TList of records is read-only). See http://forum.lazarus.freepascal.org/index.php/topic,38807.0.html
And it "was" working for other entities, because it didn't actually work.

**Comment by michaliskambi** [comment]
This is why Castle Game Engine has `TStructList` (descendant of TList from `Generics.Collections`), with helpful `List` and `L` properties. See their documentation for explanation: https://github.com/castle-engine/castle-engine/blob/master/src/base/castleutils_struct_list.inc . Feel free to use this in your programs :)

Note that Castle Game Engine uses records (and old-style "object"s) in various places, and we are 100% using Generics.Collections (not FGL) now. No exceptions. Only the deprecated unit CastleGenericLists uses FGL, and nothing in CGE uses FGL or CastleGenericLists.

We have actually discussed about a similar issue with FGL long time ago: https://github.com/castle-engine/castle-engine/issues/63 :)

**Comment by eugeneloza** [comment]
> We have actually discussed about a similar issue with FGL long time ago
Yes, that's why I had to revert to `CastleGenericLists` :) However, it's deprecated. So it's either copy-pasting `TGenericStructList` to be sure it won't be lost in some update or figuring out how to access `protected` field `FItems` in `Generics.Collections`.

**Comment by eugeneloza** [comment]
Ahh... now `TStructList` is now part of `CastleUtils`? I see. I'll try to do it this way.

**Comment by eugeneloza** [comment]
Yes, everything is working perfectly, thanks a lot!
