### ISSUE TITLE
Inverse transform matrix has NaN value inside

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#319]
Something new :)

> Warning: Transform: Inverse transform matrix has NaN value inside

**Comment by michaliskambi** [comment]
I most likely just fixed the cause of this in CGE:) Please update CGE, make sure you get the commit https://github.com/castle-engine/castle-engine/commit/10ebd4461c04a0ef4b31d89259427ceacc042db6 .

**Comment by eugeneloza** [comment]
Yes, working perfectly! Thank you! :)
