### ISSUE TITLE
Macros for %CURRENTROUTINE%?

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#320]
Try make a macros for %CURRENTROUTINE% which will automatically detect whether it's inside a function or inside a method (if `Self` exists in the namespace or not). This would simplify logging and profiling routines.
However, that's hardly possible.

**Comment by michaliskambi** [comment]
I wondered if one can use `{$if declared(Self)}` for this. See https://www.freepascal.org/docs-html/prog/progsu127.html about `declared`.

But it doesn't work for some reason. And it would also be non-perfect as "static class methods" (http://castle-engine.io/modern_pascal_introduction.html#_static_class_methods) do not have `Self`.

However, `{$if declared(ClassName)}` works perfectly! See the attached example.

```
$ fpc a.lpr 
...
$ ./a
MyMethod
ClassName is declared
MyClassMethod
ClassName is declared
MyStaticClassMethod
ClassName is declared
MyProcedure
ClassName not declared
```

[a.lpr.zip](https://github.com/eugeneloza/decoherence/files/1500256/a.lpr.zip)

**Comment by eugeneloza** [comment]
Works perfectly! Now only remake the Log procedure (simple and quick) and it's done. Thanks a lot!
