### ISSUE TITLE
CodeTools bugs

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#344]
I should really do something about CodeTools bugs with Generics.Collections (see https://github.com/eugeneloza/decoherence/issues/329) Otherwise it's just a development hell of "try-to-guess" syntax. If Generics.Collections isn't ready to work with Lazarus, then the only option I see is to roll back to FGL unit. Thou less convenient, but it still is "usable".
Doesn't work neither with FPC 3.1.1/Lazarus 1.9 nor with trunk.

**Comment by eugeneloza** [comment]
Looks like the issue is fixed in Lazarus trunk. Needs testing.

**Comment by michaliskambi** [comment]
Cool! https://bugs.freepascal.org/view.php?id=30271 indeed suggests it should be fixed.

**Comment by eugeneloza** [comment]
Yes that was exactly the reason why I tried it, and this week I've had a nice little adventure trying to make anything work, because after trying to install trunk FPC wouldn't work a tall, arguing that TObject not found :D I've been thinking of reinstalling the OS, but thanks to SymbolicFrank and Pascal, eventually I managed to fix it by a FPC patch :)

**Comment by eugeneloza** [comment]
Well... beyond the scope of the game development anyway. Closing it.
