### ISSUE TITLE
Check Window.CustomCursor and Window.Touch

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#352]
Seems like the thing I'm trying to implement

**Comment by michaliskambi** [comment]
Note that Window.CustomCursor is not implemented (although it should be trivial by just adding a TUIControl with KeepOnTop that internally shows TCastleImageControl translated by cursor position).

**Comment by eugeneloza** [comment]
Thanks, yes, I've just been thinking of implementing something like this. Thou not though UI control, but just a GL image from a TDictionary.

**Comment by eugeneloza** [comment]
Done (long ago)
