### ISSUE TITLE
Make writeable/readable configuration

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#359]
Maybe, it's the right time to start making a configuration file. Thou I hate when Linux creates a separate folder in `home` for that. Not yet sure, how to implement it. Going the "natural way" is safer. However, it creates additional problems during development, as the config should be purged by purge script, at least for now.

**Comment by michaliskambi** [comment]
If you hate having too many files/dirs in $HOME, you'll be happy to know that the FPC function for getting config dir (or CGE function on top of it) follows the xdg specification ( https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html ) and will suggest to use a name in $HOME/.config/ subdirectory. If everyone will use it (many programs do already) then the $HOME dir will be cleaner:)

**Comment by eugeneloza** [comment]
Well, at the moment I'm actually speaking of purging scripts (so that I can "delete everything" from the old version, build clean and reset to default). This would require "absolute" path to home folder (and considering me being very inattentive and inaccurate this might cause some disaster - like deleting all the contents of home folder :) e.g. due to accidentally changing `rm -r ~/.config` into `rm -r ~/. config`). I feel safe about making anything in the game folder, as I have a few dozens of backups including online GIT. But I wouldn't like to mess with home folder.

**Comment by eugeneloza** [comment]
Seems to be solved by https://github.com/eugeneloza/decoherence/commit/b5e07419f87bf775144cacadc6d128523e3808cf except for a bug #520 
To cut it short: `ApplicationData` is used for Desktop and `ApplicationConfig` for everything else.
