### ISSUE TITLE
Test drag-n-drop

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#383]
I'm afraid it might work really wrong (e.g. detecting a set of elements below the current element to drop an item to specific slot).

**Comment by eugeneloza** [comment]
Of course it's not working at all :D
Ok, that's for tomorrow.

**Comment by ResonantExplosion** [comment]
Working smoothly, however there are 3 bugs here.

1. `CanDrag` doesn't work without `CanMouseOver` as `MouseOver` returns nil in `doMouseDrag`

**Comment by ResonantExplosion** [comment]
2. `onMouseOver` works only in case the dragging element is within the parent element, which is expected and correct behavior. It must preform some useful action at `onDrop`, like returning to initial location or  attached to a new parent if it can accept a drop (e.g. an inventory slot).
3. The drawing sequence is fixed. I.e. the dragged element is not on the top of the interface and can get behind other elements which is very wrong, as this situation is very likely to happen in interface slots.

**Comment by ResonantExplosion** [comment]
I'm not sure how Arrangers will begave

**Comment by ResonantExplosion** [comment]
behave* (or better, composite elements will drag only themselves, not children).
However, composite elements aren't expected to be dragged. It should work only with item pics and maybe portraits (without overlays dragged)

**Comment by eugeneloza** [comment]
Concerning "2" - `TryDropHere` should find an element and run its `CanDropHere` if assigned - accepting the "droppoed" element. In this way we can have the slot itself "testing" against which objects can be dropped here (e.g. inventory slot can accept any item, while equipment slot can accept only specific type of items)

**Comment by eugeneloza** [comment]
Closing this for now. Everything's working, and when something will not work, open a new issue.
