### ISSUE TITLE
Force external animation

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#453]
(trying to solve #452 )
GetCurrentAnimationState -> Natural/External animation
No guarantee that'll work.

**Comment by eugeneloza** [comment]
Expecting conflict with #383

**Comment by eugeneloza** [comment]
Now `Update` is called from `Draw`. This hinders changing `Current` by parent. If make `Update` recursive and call it before the whole `Draw` tree - and update `Children` before `Parent`, there is one more level, allowing to change `Current` of Children, without reseting their animation and `Next`.

However, this still won't work if there is a sequence of `Arranger`s:
Child arranger will arrange its children
Parent arranger will arrange Child arranger
Child arranger's children won't get updated

Relatively normal situation for
DCharacter -> DPerks -> DPerkItem (a sequence of at least three arrangers).

**Comment by eugeneloza** [comment]
Taking a deep breath and thinking aloud.

So we have an animated `Parent`.
Parent calls `Update` (let's consider it separate from `Draw`).
It calculates its current animation state `Current`.
And modifies `Children`'s `Current` to fit its `Current` by `ArrangeChildren` if requested to.

If `Child` calls `Update` at this point it will overwrite `Current` with self-determined value (as it does now).
If `Child` called `Update` before, then it wasn't provided with a valid `Current` in `ArrangeChildren`

So, thinking another way:
We call `Update` for `Parent`
We `Update` `Children` recursively - their unarranged `Current` determined
We call `ArrangeChildren` and overwrite a second generation _<------ here is the problem_
At this point if we want to go "deeper" in generations we have to call `ArrangeChildren` recursively if `Children[i] is TAbstractArranger`.

Makes sense. Thou unsure if it'll work as expected.

**Comment by eugeneloza** [comment]
We'll need a virtual empty `ArrangeChildren` on every Interface element, because theoretically there might be a sequence:
Arranger -> NormalElement -> Arranger
which will be cut by `is TAbstractArranger` and won't go deeper.

**Comment by eugeneloza** [comment]
Wait, do I really need to call `ArrangeChildren` every frame? If I copy just `Arranger` animation, that won't be pixel-perfect (and sometimes the children may be "assembled" independently), but that doesn't seem anywhere near "bad", doesn't it?

**Comment by eugeneloza** [comment]
Yes, I need to `ArrangeChildren` only on changing `Next` (i.e. by `SetSize` i.e. making it `virtual`).

So, the `Update` remains unchanged.
Overriding `SetSize` calls recursively `ArrangeChildren` and sets their `Next`s based on `Parent` `Next` using `Parent.SetSize` parameters to (first of all, copy animation style and duration).

I'll try this solution.

**Comment by ResonantExplosion** [comment]
Arrange children iterates only once. DAbstractArranger may be only child of another DAbstractArranger. Easy rule, much less problem.
