### ISSUE TITLE
Right click behavior

### ISSUE THREAD

**Issue by ResonantExplosion** [eugeneloza/decoherence#491]
```
Interface IHint
Procedure showhint;
End;
```
Will be different for items, perks, etc.
R-click on portraits will enter inventory / party menu, not show hint.
Maybe not show hint, but onRightClick? As s procedure pointers

**Comment by eugeneloza** [comment]
I don't like Right-click term, as it also a Long-click. I wonder, if there is any standard term for that stuff, like `PrimaryClick` (action) and `SecondaryClick` (info, auxiliary)

**Comment by eugeneloza** [comment]
onRightClick may be easily defined as "show hint" and overriden in complex situations. Usually it's only 2 versions of these: "plain text in a frame", and "image + plain text in a frame" (maybe, leave only this option? some items would just have a "Generic" item image (kinda game logo)).
