### ISSUE TITLE
Return profiler

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#507]

**Comment by ResonantExplosion** [comment]
Maybe already return the profiler? And patch it thoroughly

**Comment by eugeneloza** [comment]
Moving that for a bit later. There are higher-priority tasks right now.

**Comment by eugeneloza** [comment]
Hardly it's possible to fix https://github.com/eugeneloza/decoherence/issues/604 without the profiler. Restarting the work.

**Comment by eugeneloza** [comment]
All up and working. Just to instrument the code...
