### ISSUE TITLE
Move all folder stuff to hdd-related uñit

### ISSUE THREAD

**Issue by ResonantExplosion** [eugeneloza/decoherence#524]
And try collecting all read/write routines in separate units in src/readwrite

**Comment by eugeneloza** [comment]
Not sure if it's possible to make it all clean due to #499 but maybe this is a way to go.

> DecoHDD
> DecoFolders
> DecoReadWrite

seems ok. I wonder if `DecoImageLoader` and the like should also go into that group (everything that works on read-write operations directly)? Probably not.
