### ISSUE TITLE
XMLDoc.CreateElement requires string conversion

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#526]
> decofiles.pas(142,38) Warning: Implicit string type conversion from "AnsiString" to "WideString"

**Comment by michaliskambi** [comment]
You can add `CastleXMLUtils` to uses clause and use `CreateChild` : https://github.com/castle-engine/castle-engine/blob/master/src/files/castlexmlutils.pas#L1020

**Comment by eugeneloza** [comment]
Oh, thanks, Michalis! I was just looking to look for or implement something like that :) That makes things much much easier.
