### ISSUE TITLE
Force Next State

### ISSUE THREAD

**Issue by ResonantExplosion** [eugeneloza/decoherence#537]
Requiring to set next, reset animation, setsize the same value again to fire all events including sizechanges every time is counterintuitive. Make a procedure that will preform all the corresponding tasks in one call. Thou it looks like a minor architecture bug to me.

**Comment by ResonantExplosion** [comment]
Extremely important for Arranging Children

**Comment by eugeneloza** [comment]
Hmm, I'm not really sure how the animation pipeline works for `Arrangers` at all. Need to double-check it again. In short: `ForceSize` won't work as we need to set both `Last` and `Next` state based on `Self.Current` (or `Child.Current`?!) and `Self.Next`.

**Comment by ResonantExplosion** [comment]
Ok. It seems that there's no bug. We need to set the initial and final state of the child to animate it properly. This is inavoidable unless we are 100% sure the Child.Current is exactly the expected initial state. This should be true if the child is arranged not the first time or if it was properly scaled on creation. In a perfect situation this should be true, but I wouldn't count on that always. So, yes. We need to force both initial and next state of the child to be on the safe side. And we need a better tool to do that (in 1 line).

**Comment by eugeneloza** [comment]
Well, basically it's fixed now. I only hope it'll work as expected not only for `DCenterArranger`.
