### ISSUE TITLE
30FPS?!

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#604]
What the hell happened? Why only 30FPS on a very simple scene?!

**Comment by eugeneloza** [comment]
Clean interface - 60FPS
add Wind - 60FPS
add Interface slot prototype - 60FPS
**add Large frame (DRectagonalFramedElement) - 27 FPS**

**Comment by eugeneloza** [comment]
Everything else altogether - 60FPS
There is some bug with an empty `DRectagonalFramedElement` (two filled instances (smaller in size thou) don't make any FPS drop)?

**Comment by eugeneloza** [comment]
Nope, it's the size that matters large `DPlayerBars` drop FPS down to 8. What could it be?

**Comment by eugeneloza** [comment]
Upd: same FPS drop with animations disabled.

**Comment by eugeneloza** [comment]
Error was so obvious... :D

**Comment by michaliskambi** [comment]
Ouh :) I feel your pain. Well, every bug is obvious after solving it :)

**Comment by eugeneloza** [comment]
Yeah. Feeling so stupid :). I was suspecting that the frame was reinitialized (scaled and burned) every frame, but couldn't believe I really did something as obvious as forgetting setting "initialized" to true :)
