### ISSUE TITLE
Hint: Inlining disabled

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/decoherence#96]
At some point I've started getting a verbose error:

> Hint: "inherited" not yet supported inside inline procedure/function
> Hint: Inlining disabled

without pointing to a specific line of code.
I'm pretty sure I'm not using "inherited" in inlined procedures... where could the error be???

see more: http://forum.lazarus.freepascal.org/index.php/topic,37791.msg255506/topicseen.html

**Comment by eugeneloza** [comment]
I've tested and confirmed that this hint relates to my code, not Castle Game Engine or FPC. If I disable inline everything works fine.

**Comment by eugeneloza** [comment]
Verbose: Compiling ./src/decoperks.pas
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

Verbose: Compiling ./src/decoload3d.pas
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

Verbose: Compiling ./src/decofont.pas (CONTAINS NO INLINES!)
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

Verbose: Compiling ./src/decoloadscreen.pas
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decoplayercharacter.pas(195,4) ...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decoabstractworld3d.pas(112,22) ...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decoactor.pas(231,33)...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decointerface.pas(202,64)...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decodungeongenerator.pas(1270,31)...
decodungeongenerator_calculatefaces.inc(20,10)...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decodungeonworld.pas(222,4)...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

decosound.pas(473,4)...
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled
Hint: Inlining disabled

**Comment by eugeneloza** [comment]
total 153 times (that might be more than actual count of inlined procedures!)
I have no idea where to start looking for those.
[inlinedisabled.tar.gz](https://github.com/eugeneloza/decoherence/files/1238627/inlinedisabled.tar.gz)
Test doesn't show any error like that... No matter how hard I try to cause the same hint.

Well... if it's **not yet implemented**, maybe I should give up and just wait until it's implemented? :)

**Comment by eugeneloza** [comment]
@michaliskambi thanks a lot for your answer at Lazarus forum. I should check those issues.
As for the 1st statement. Yes, I'm 95% sure that it's not the problem of CastleVectors, because when I disable all inlining in Decoherence (by a compiler directive) the hint goes away.
Thou, I have another issue with those hints/warnings (very often they just go missing and their amount changes greatly from compile to compile): http://forum.lazarus.freepascal.org/index.php/topic,36216.msg257298.html

**Comment by michaliskambi** [comment]
> Thou, I have another issue with those hints/warnings (very often they just go missing and their amount changes greatly from compile to compile): 

I can't help you much with this, other than saying that I never observed it :) If you *really* clean your project, then recompiling it will definitely reproduce all the hints/warnings/etc. So you must have some *.ppu / *.o files left somewhere.

You can try compiling with -vu to see where the compiler searches for your units. If the compiler is picking up a pre-compiled unit from some surprising location, the output with -vu will show this. (Beware, it will be *long* output, so it's best to redirect it to some file).

**Comment by eugeneloza** [comment]
> You can try compiling with -vu to see where the compiler searches for your units.

Nope, it doesn't show anything surprising. Neither Project>ShowProjectPPUFiles shows any strange locations...
Maybe, something's wrong with my installation?

**Comment by eugeneloza** [comment]
No longer an issue with FPC 3.1.1
